### ISSUE TITLE
content failed to load for me

### ISSUE THREAD

**Issue by eelfroth** [nullself/nullself.github.io#1]
Hey, I'm getting an empty content div in Firefox 66.0.4 and the following error message in the developer cosole:

> TypeError: line.matchAll is not a function[Learn More] lipu.js:28:25
>     tpl https://nullself.github.io/assets/scripts/lib/lipu.js:28
>     lipu https://nullself.github.io/assets/scripts/lib/lipu.js:102
>     forEach self-hosted:262
>     lipu https://nullself.github.io/assets/scripts/lib/lipu.js:67
>     route https://nullself.github.io/assets/scripts/main.js:17
>     <anonymous> https://nullself.github.io/assets/scripts/main.js:29

**Comment by nullself** [comment]
I hadn't actually tested in FF yet, just Chrome. Seems maybe FF doesn't support matchAll for some reason, I'll have to look into why that is, and try to find a fix. Thanks!

**Comment by nullself** [comment]
Interesting, Mozilla just recently added support for `matchAll` in **v67**:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#JavaScript

Since it's going to be a feature for 67 and beyond, I'm considering not spending the time to fix it, as I intended to build this site using js features that may not work on older versions of browsers. I didn't expect "older versions" to be the second most recent FF version though haha

I appreciate you bringing this to my attention :)

**Comment by dym-sh** [comment]
on my end its the opposite: Chrome throws matchAll error, but Firefox is ok

also same error for all browsers on iOS
